### ISSUE TITLE
Handling of lower-case protein sequences

### ISSUE THREAD

**Issue by kazumaxneo** [desmid/mview#21]
I am trying to visualize the MSA of genes that are coding in two separate positons. 
I would be happy if I could display the amino acid sequence of one part in lowercase letters.
When I tried, I got the following error
$ Sequence lengths differ for output format 'mview' - aborting

I use MSA files like this one.
>f__Nostocaceae_separate_coding_coded_000316665.1_6271
MTDENIRQIAFYGKGGIGKSTTSQNTLAAMAEMGQRIMIVGCDPKADSTRLMLHSKAQTT
VLSLAAERGAVEDLELEEVMLEGFRGVRCVESGGPEPGVGCAGRGIITSINFLEENGAYQ
DLDFVSYDVLGDVVCGGFAMPIREGKAQEIYIVTSGEMMAMYAANNIARGVLKYAHSGGV
RLGGLICNSRNVDREVELIETLADRLNTQMIHFVPRDNIVQHAELRRMTVNEYAPDSNQA
KEYATLATKIINNKNLAIPTPNELTTLTFVICSLKS*mdeleallvefgildddtkhadi
igkkaeevpas*
>f__Nostocaceae_separate_coding_coded_000317435.1_405
MAVDKSIRQIAFYGKGGIGKSTTSQNTLAAMAEMGQRILIVGCDPKADSTRLMLHSKAQT
TVLSLAAERGAVEDLELEEVMLTGFRGVKCVESGGPEPGVGCAGRGIITAINFLEENGAY
QDVDFVSYDVLGDVVCGGFTNYH*mpiregkaqeiyivtsgemmamyaanniargvlkya
htggvrlgglicnsrkvdrevelietlakrlntqmihfvprdnivqhaelrrmtvneyap
dsdqgneyrtlakkiinnknltiptpiemdelealliefgildddtkhaapeikaaask*
>f__Nostocaceae_separate_coding_coded_002368075.1_2211
MSDEKIRQIAFYGKGGIGKSTTSQNTLAAMAEMGQRILIVGCDPKADSTRLMLHSKAQTT
VLHLAAERGAVEDLELHEVMLTGFRGVKCVESGGPEPGVGCAGRGIITAINFLEENGAYT
DLDFVSYDVLGDVVCGGFAMPIREGKGGLFRVFVGAIV*mmamyaanniargilkyahsg
gvrlgglicnsrktdrehelietlakrlntqmihfvprdnivqhaelrrmtvneyapdsn
qaneyralakkiienknltiptpiemdeleallieygildddskhaeiigkpasatk*

Best wishes,

**Comment by desmid** [comment]
I never saw your message, sorry!

The problem is not with the lowercase characters. Your three sequences of characters have different lengths. MView does not align the sequences - it expects the input to be aligned already. An MSA program (or you if you make the alignment by hand) will insert gaps in some sequences (marking insertion/deletions) to make the output rows all have the same length. The gap characters look like dashes '-' or dots '-'. Perhaps you edited them out?
